<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>RDPManager</RootNamespace>
    <AssemblyName>小白服务器管理器</AssemblyName>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="work\**\*.cs" />
    <EmbeddedResource Include="favicon.ico">
      <LogicalName>RDPManager.favicon.ico</LogicalName>
    </EmbeddedResource>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
  </ItemGroup>
</Project>
